In [1]:
import numpy as np

# Maths with matrix

In [4]:
A = np.array([[1, 2],
              [4, 5]])

In [5]:
A

array([[1, 2],
       [4, 5]])

In [7]:
B = np.array([[6, 5],
              [3, 2]])
B

array([[6, 5],
       [3, 2]])

## Sum of matrix

In [9]:
print(A)
print("+")
print(B)
print("=")
print(A+B)

[[1 2]
 [4 5]]
+
[[6 5]
 [3 2]]
=
[[7 7]
 [7 7]]


## Substraction

In [10]:
print(A)
print("-")
print(B)
print("=")
print(A-B)

[[1 2]
 [4 5]]
-
[[6 5]
 [3 2]]
=
[[-5 -3]
 [ 1  3]]


## Multiplication

In [12]:
# Multiplicación Escalar
print(A)
print("*")
print(B)
print("=")
print(A*B)

[[1 2]
 [4 5]]
*
[[6 5]
 [3 2]]
=
[[ 6 10]
 [12 10]]


In [15]:
# Multiplicación Vectorial
print(A)
print("X")
print(B)
print("=")
print(np.dot(A, B))

[[1 2]
 [4 5]]
X
[[6 5]
 [3 2]]
=
[[12  9]
 [39 30]]


## Reverse

In [16]:
np.linalg.inv(A)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [17]:
print(A, "^-1")
print("=")
print(np.linalg.inv(A))

[[1 2]
 [4 5]] ^-1
=
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


In [19]:
identidad = np.array([[1,0],
                      [0,1]])
np.linalg.inv(identidad)

array([[1., 0.],
       [0., 1.]])

In [22]:
print(A)
print("X")
print(identidad)
print("=")
print(np.dot(A, identidad))

[[1 2]
 [4 5]]
X
[[1 0]
 [0 1]]
=
[[1 2]
 [4 5]]


In [21]:
np.array([[1,0,0],
          [0,1,0],
          [0,0,1]])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## Determinant

In [23]:
np.linalg.det(A)

-2.9999999999999996

In [24]:
A = np.array([[1, -2],
              [1, -1]])
np.linalg.det(A)

1.0

## Range of an matrix

In [33]:
A = np.array([[1,2], 
              [2,4]])

In [34]:
np.linalg.det(A)

0.0

In [35]:
A = np.array([[1,2], 
              [2,4], 
              [4,8]])

In [ ]:
np.linalg.det(A)

In [31]:
np.linalg.matrix_rank(A)

1

In [32]:
A = np.array([[1,2], 
              [2,4], 
              [4,8], 
              [1,3]])
np.linalg.matrix_rank(A)

2

## Systems of equations with Matrices

Suppose we have the following problem:
* Juan is twice Maria's age
* Juan is 15 years older than Maria

The system of equations would be the following

```
X - 2Y = 0
X - Y = 15
```
The system expressed in Matrix form would be the following:

$
\begin{bmatrix}
1 & -2 \\
eleven \\
\end{bmatrix}
\begin{bmatrix}
X \\
AND \\
\end{bmatrix}
=
\begin{bmatrix}
0 \\
fifteen \\
\end{bmatrix}
$

Reducing the notation, the system would be:

\begin{equation}
A \cdot X = B
\end{equation}
\begin{equation}
X = A^{-1} \cdot B
\end{equation}

In [37]:
A = np.array([[1, -2],
              [1, -1]])

B = np.array([0,15])

In [38]:
A

array([[ 1, -2],
       [ 1, -1]])

In [39]:
B

array([ 0, 15])

In [41]:
inv_A = np.linalg.inv(A)
inv_A

array([[-1.,  2.],
       [-1.,  1.]])

In [43]:
# Producto Vectorial
np.dot(inv_A,B)

array([30., 15.])

## SI, SCI y SCD

In [44]:
## SI el DET != 0 -> SCD

## SI el DET == 0 
   # SCI -> LD en A y B
   # SI  -> LD solo en A

### SCD

In [45]:
# SCD 
A = np.array([[1, -2],
              [1, -1]])

B = np.array([0,15])

np.linalg.det(A)

1.0

### SCI

In [49]:
# SCI 
A = np.array([[1, -2],
              [2, -4]])

B = np.array([0, 0])

np.linalg.det(A)

0.0

In [47]:
# SCI pq DET = 0 y rango(A_B) = 1
A_B = np.array([[1, -2, 0],
                [2, -4, 0]])
np.linalg.matrix_rank(A_B)

1

# SI

In [50]:
# SI 
A = np.array([[1, -1],
              [1, -1]])

B = np.array([15, 10])
np.linalg.det(A)

0.0

In [51]:
A_B = np.array([[1, -1, 15],
                [1, -1, 10]])
np.linalg.matrix_rank(A_B)

2